<div class="actions clearfix row">
    <div class="btns span12">
        <a class="btn submit btn-info" href="/admin/index/save" title="Criar Post">Criar Post</a>
    </div>
</div>
<br> 
<h2>Lista de Posts</h2>
<table class="table-hover table">
    <thead>
        <tr>
            <th>Título</th>
            <th>Texto</th>
            <th width="150" class="center">Data de Cadastro</th>
            <th width="120" class="center">Opções</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($posts as $post): ?>
            <tr>
                <td><?php echo $this->escapeHtml($post['title']); ?></td>
                <td><?php echo $this->escapeHtml($post['description']); ?></td>
                <td class="center">
    <?php
    //echo $this->dateFormat($post['post_date'], IntlDateFormatter::SHORT, IntlDateFormatter::SHORT, 'pt_BR');
    echo $post['post_date'];
    ?>
                </td>
                <td class="center">
                    <a href="/admin/index/save/id/<?php echo $post['id']; ?>" title="Editar" class="btn"><i class="icon-edit"></i></a>
                    <a href="/admin/index/delete/id/<?php echo $post['id']; ?>" rel="confirmation" title="Deseja excluir este registro?" class="btn"><i class="icon-remove"></i></a>
                </td>
            </tr>
<?php endforeach; ?>
</table>
<?php
    echo $this->paginationControl($posts, 'Sliding', 'partials/paginator/control.phtml');
?>